# Site settings
title: Pieter Willekens
description: > # this means to ignore newlines until "baseurl:"
  Personal site || portfolio of Pieter Willekens.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
twitter_username: 1pieter
github_username:  pataar
trakt_username:  pataar
lastfm_username:  pataar
github_username:  pataar

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

sass:
  sass_dir: _sass/
  style: :compressed
  sourcemaps: true

gems:
  - jekyll-babel